### ISSUE TITLE
Add multiple servers

### ISSUE THREAD

**Issue by johannesCmayer** [djmango/obsidian-transcription#13]
It would be kind of good (at least for me, maybe this is niche) if you could specify a list of servers in the settings, such that you try to connect to each of the servers in turn, until one is found that works. I have one GPU server, but it is only available on a specific wifi, and not from my home. I have another GPU server that is accessible from everywhere. It would be great if that server could be accessed automatically when the other is not available.

**Comment by bscholer** [comment]
+1
