### ISSUE TITLE
404 error on ASR server

### ISSUE THREAD

**Issue by dahifi** [djmango/obsidian-transcription#23]
Currently 3.06 still works, but I installed transcription in two additional notebooks and was unable to get a response with 3.1.5. 

Debug mode is just showing a 404. 

I've gone back and forth between machines and notebooks. Will find time to troubleshoot next week.

**Comment by dahifi** [comment]
Fixed in https://github.com/djmango/obsidian-transcription/pull/24

**Comment by djmango** [comment]
> Fixed in https://github.com/djmango/obsidian-transcription/pull/24

Thanks for this! Missed it initially - will release a patch update now
