### ISSUE TITLE
Youtube integration

### ISSUE THREAD

**Issue by g1ronn1mo** [djmango/obsidian-transcription#27]
Hey, for now there is no way to transcribe a yt video. Is there a plan for implementing this feature?

**Comment by djmango** [comment]
I'm not seeing a way to cleanly integrate a [yt-dlp](https://github.com/yt-dlp/yt-dlp)-like program, which in my head is the most robust solution for implementing something like this. A dynamic binary download could be possible based on system architecture.. I believe some plugins that use OCR do this. Would likely not work on mobile.

Open to PRs or suggestions here but until a cleaner solution is presented it's too much bandwidth for me and not planned. Appreciate the suggestion though, keep em rolling :D
