### ISSUE TITLE
Typo in the main link

### ISSUE THREAD

**Issue by dsalavei** [djmango/obsidian-transcription#28]
https://github.com/djmango/obsidian-transcription/blame/e43aae9740792401639204ca0d8636ca4940aa4b/README.md#L3C25-L3C66

The link [Swiftink.io](https://wwww.swiftink.io/) doesn't work because of 4 wwww.

P.S. I really appreciate the work you're doing, so decided to return the favor :)

**Comment by djmango** [comment]
Thanks @dsalavei! Just pushed a fix, totally missed this. If theres any feature additions you think would be nice to have or bugs you find don't hesitate to reach out!
