### ISSUE TITLE
It would be nice to have an option to show the timestamp

### ISSUE THREAD

**Issue by ruanwz** [djmango/obsidian-transcription#3]
Can you please add an option to show the timestamp? Because the long text without timestamp are hard to locate the key conversion. Thanks!

For example:
``` 

           var transcription = ""                                              
            for (var s of response.json.segments ) { transcription += Math.floor(s.start) + ': ' + s.text + "\n"}

```

**Comment by djmango** [comment]
Thanks for the example code! I've added the feature in [the latest commit](https://github.com/djmango/obsidian-transcription/commit/9ad5c3eb5b6a6c17249171b5622bcd72ee4f9eaa). Demo below


https://user-images.githubusercontent.com/28496988/208805440-27fdd7a7-5d51-4f95-8f8b-debfb61a70e1.mov
