### ISSUE TITLE
No Timestamps Produced When Using Whisper

### ISSUE THREAD

**Issue by funderburk5** [djmango/obsidian-transcription#31]
When using whisper. I've noticed that my results don't include the timestamps. How can I address this issue?

**Comment by djmango** [comment]
Could you send a screenshot if your settings page? What version of Whisper ASR and the plugin are you using?

**Comment by djmango** [comment]
Lol i remember doing stuff like that. Good luck. I recommend manjaro

**Comment by gon-pm** [comment]
I got the same result using Whisper ASR, there's no option to enable timestamps

![imagen](https://github.com/djmango/obsidian-transcription/assets/47288005/a811cb76-30c5-4b6b-9d9b-d03e9e058641)

**Comment by djmango** [comment]
It seems that the output format from Whisper ASR is slightly different and does not work with the timestamp function currently. Will require a new function to handle it, I don't have bandwidth right now to implement it

**Comment by bscholer** [comment]
Added in #46, along with some description of what the word timestamps option seems to actually do.
