### ISSUE TITLE
Connection reset error

### ISSUE THREAD

**Issue by derekvan** [djmango/obsidian-transcription#4]
I keep getting this error:

plugin:obsidian-transcription:118 Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
    at SimpleURLLoaderWrapper.emit (node:events:390:28)
eval	@	plugin:obsidian-transcription:118
Promise.catch (async)		
editorCallback	@	plugin:obsidian-transcription:116
await in editorCallback (async)		
e.mobileOnly.$b.isMobile.e.checkCallback	@	app.js:1
BB	@	app.js:1
t.onChooseItem	@	app.js:1
eval	@	plugin:hotkey-helper:1
i	@	plugin:hotkey-helper:1
t.onChooseSuggestion	@	app.js:1
t.selectSuggestion	@	app.js:1
e.useSelectedItem	@	app.js:1
(anonymous)	@	app.js:1
e.handleKey	@	app.js:1
e.onKeyEvent	@	app.js:1

**Comment by djmango** [comment]
> I keep getting this error:
> 
> plugin:obsidian-transcription:118 Error: net::ERR_CONNECTION_RESET at SimpleURLLoaderWrapper. (node:electron/js2c/browser_init:101:7169) at SimpleURLLoaderWrapper.emit (node:events:390:28) eval @ plugin:obsidian-transcription:118 Promise.catch (async) editorCallback @ plugin:obsidian-transcription:116 await in editorCallback (async) e.mobileOnly.$b.isMobile.e.checkCallback @ app.js:1 BB @ app.js:1 t.onChooseItem @ app.js:1 eval @ plugin:hotkey-helper:1 i @ plugin:hotkey-helper:1 t.onChooseSuggestion @ app.js:1 t.selectSuggestion @ app.js:1 e.useSelectedItem @ app.js:1 (anonymous) @ app.js:1 e.handleKey @ app.js:1 e.onKeyEvent @ app.js:1

Could you provide environment details? What device, OS, what version/model of Whisper ASR are you using, etc.

**Comment by derekvan** [comment]
Mac 12.6
Obsidian 1.0.3
Running Whisper from the docker hub: https://hub.docker.com/r/onerahmet/openai-whisper-asr-webservice

**Comment by djmango** [comment]
> Mac 12.6 Obsidian 1.0.3 Running Whisper from the docker hub: https://hub.docker.com/r/onerahmet/openai-whisper-asr-webservice

What happens when you go to http://localhost:9000/docs?

**Comment by derekvan** [comment]
Hmm, nothing. Looks like I'm having trouble getting the whisper thing installed. I don't really have experience with docker. I'll keep working on it!
