### ISSUE TITLE
m4 files aren't transcribing

### ISSUE THREAD

**Issue by amunrarara** [djmango/obsidian-transcription#42]
Cheers @djmango 

Are m4a files supported by your plugin here? I can't seem to get them to properly transcribe with locally-running Whisper in Docker. I've had great luck with mp3, so my setup should be fine, but m4a isn't working.

**Comment by djmango** [comment]
You'll have to implement ffmpeg into the transcribe API server unfortunately, out of scope of the plugin

**Comment by amunrarara** [comment]
Would you accept a PR that implemented ffmpeg?

**Comment by djmango** [comment]
If it was robust, worked for everyone, and required no action on the user's part, then sure. When I looked I didn't see a great way to do it, you're welcome to though

**Comment by amunrarara** [comment]
Awesome, thanks @djmango , I'll give it a look
