### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Calorion** [djmango/obsidian-transcription#43]
I'm trying to transcribe an hour-long file from Apple Voice Memos on iPad, but the upload to Swiftlink seems to time out after about 6%. The "uploading" notification just vanishes.

**Comment by Calorion** [comment]
Same thing is happening on the Mac (Big Sur).

**Comment by Calorion** [comment]
Well. It looks like the upload worked after all, at least on the Mac. I'm not at all sure that it continues to upload after the notification vanishes on iOS, but it seems to on the Mac. However, that is really unclear. Don't include a percentage at all if the notification that shows the percentage is going to vanish! Just say "uploading" and leave it at that.

**Comment by djmango** [comment]
Could you try now? Have improved TUS
