### ISSUE TITLE
login, does not work

### ISSUE THREAD

**Issue by Jirido** [djmango/obsidian-transcription#51]
Hi I use obsidian at linux and when i tryn login with email or with gmail or with github(I'm not signed up with github) Nothing happens.
Is there some setting I can write directly in data.json that let me store my login credentials?

**Comment by djmango** [comment]
You can paste in your key (it's in the query params of callback, after you login) to `data.json`

Typically located in `VAULT/.obsidian/plugins/obsidian-transcription/data.json`

The keys are `swiftink_access_token` and `swiftink_refresh_token`
