### ISSUE TITLE
Whisper ASR is broken

### ISSUE THREAD

**Issue by jack2game** [djmango/obsidian-transcription#52]
This plugin cannot work with the Whisper ASR Webservice anymore. It sends audio file to the docker, but cannot pick up the response properly.

**Comment by djmango** [comment]
Has the Whisper ASR response format changed? If so, can submit a PR or use the ASR docker image versioned before the format change

**Comment by quantology** [comment]
I might be seeing the same issue:

```
Error with URL: http://localhost:9000/asr?output=json&word_timestamps=true&language=en TypeError: Cannot read properties of undefined (reading 'map')
```

I've replicated the above error on Whisper ASR versions 1.3.0 (latest) and also 1.2.4 and 1.1.1. It seems to be failing [here](https://github.com/djmango/obsidian-transcription/blob/master/src/utils.ts#L65). It looks like the code above expects `rawResponse.segments` to be an array of arrays, whereas I'm seeing it as an array of `Segment[]`, where `Segment` is like:
```typescript
interface Segment {
  avg_logprob: number;
  compression_ratio: number;
  end: number;
  id: number;
  no_speech_prob: number;
  seek: number; 
  start: number;
  temperature: number;
  text: string;
  tokens: number[];
}
```
I'm happy to revert to a previous version of the docker image -- does anyone know what the latest functional version of `whisper-asr-webservice` is?

**Comment by Xeelix** [comment]
> I might be seeing the same issue:
> 
> ```
> Error with URL: http://localhost:9000/asr?output=json&word_timestamps=true&language=en TypeError: Cannot read properties of undefined (reading 'map')
> ```
> 
> I've replicated the above error on Whisper ASR versions 1.3.0 (latest) and also 1.2.4 and 1.1.1. It seems to be failing [here](https://github.com/djmango/obsidian-transcription/blob/master/src/utils.ts#L61). It looks like the code above expects `rawResponse.segments` to be an array of arrays, whereas I'm seeing it as `Segment[]`, where `Segment` is like:
> 
> ```ts
> interface Segment {
>   avg_logprob: number;
>   compression_ratio: number;
>   end: number;
>   id: number;
>   no_speech_prob: number;
>   seek: number; 
>   start: number;
>   temperature: number;
>   text: string;
>   tokens: number[];
> }
> ```
> 
> I'm happy to revert to a previous version of the docker image -- does anyone know what the latest functional version of `whisper-asr-webservice` is?

Hey! Were you able to solve the problem?

**Comment by djmango** [comment]
Ah in that case this might be related to https://github.com/djmango/obsidian-transcription/pull/50 @bscholer

**Comment by djmango** [comment]
Thanks for investigating @dahifi - i will corroborate your findings and release an update later today accordingly

**Comment by dahifi** [comment]
I found the line here: https://github.com/djmango/obsidian-transcription/pull/50/files#diff-0f4208f0163c212f445df35fc43b99ceb09432700a33b38b514883c99c7d6169R131

I'm going to grab lunch then would like to do the PR myself, kind ser.

**Comment by bscholer** [comment]
I haven't looked close at the code yet, but this does seem like it's due to my PR #50. Will leave for @dahifi to patch unless you'd like me to!

**Comment by djmango** [comment]
Gotcha, much appreciated

**Comment by dahifi** [comment]
Actually got it done _before_ my sandwich cooked, this should do the trick. Can we get a release quickly so I don't have to downgrade my Notebook plugin? @djmango

**Comment by dahifi** [comment]
Please disregard that, I should probably take care to validate the response. Probably rushing because I was hungry. Give me an hour to load up my Obsidian dev vault and test everything.

**Comment by dahifi** [comment]
Ok, so I have no idea which version I was using before, and there's a lot that seems different here. WhisperASR expects the file to be a multipart form, e.g.
```
curl -X 'POST' \
  'http://192.168.1.201:9000/asr?task=transcribe&encode=true&output=json&diarize=false' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'audio_file=@Recording 20231008113030.webm;type=video/webm'
  ```
  
  Where it looks like you're using octet-streams in the request body?
 
I've had bad luck trying to get things working in my dev notebook. I went back through all the various commits that modified that function and finally wound up on the [last contribution I did back in October](e019f0eddd12c368003c28e1d4a53e5b7feb1756), which should be v.3.1.6. 

For now I recommend ASR users load up that version, I'm not sure I want to spend more time on it. DJ may want to reconsider supporting it since Swiftlink has diverged from it so much now. Might just want to make a note in the readme and leave it at that.

**Comment by bscholer** [comment]
It looks like this issue does not occur when using `ASR_ENGINE=faster_whisper`. Seems like there is an inconsistency between the engines in https://github.com/ahmetoner/whisper-asr-webservice

**Comment by bscholer** [comment]
Doing further investigation, it looks like `ASR_ENGINE=openai_whisper` returns a structure that looks like this (notice the named fields in the `segments` array):
<img width="876" alt="image" src="https://github.com/djmango/obsidian-transcription/assets/2822945/24c6cd5a-e189-4a61-878d-5b88d8530e34">

`ASR_ENGINE=faster_whisper` instead returns a structure that looks like this (notice the lack of named fields). Although I hate this format, this is what I wrote the code to expect.
<img width="884" alt="image" src="https://github.com/djmango/obsidian-transcription/assets/2822945/b1923268-51c7-4741-9301-0ebcc0ceb2e4">

I'll open up an issue on https://github.com/ahmetoner/whisper-asr-webservice to try to standardize this, but for now, I'll just tweak the code to handle both so we can get this issue fixed.

**Comment by djmango** [comment]
Update released
