### ISSUE TITLE
SwiftInk no longer works; assuming temporary issues?

### ISSUE THREAD

**Issue by smallstepman** [djmango/obsidian-transcription#56]
after purchasing pro license (currently on trial) and successfully transcribing several files, I'm no longer able to get the files to transcribe (even the ones that worked ok yesterday). On the website I can see "Failed". Any idea how to fix?

**Comment by whosbad19** [comment]
I have the same issue, the transcription worked very well during my free trial but today I've purchased today the pro license and I was unable to transcribe any of my voice note. "Error Transcribing file: Swiftink failed to transcribe the file.
![Capture](https://github.com/djmango/obsidian-transcription/assets/154232900/be8a59f1-52b0-4101-bbeb-ba3b45a7cd3e)

**Comment by djmango** [comment]
Hey gang, this was my mistake - forgot to update the card for our backend services when it expired! Everything is up and running now, apologies for the inconvenience!

**Comment by whosbad19** [comment]
@djmango The 502 error came back 😉 Can you fix this please? 🙏
