### ISSUE TITLE
Can't find transcription line

### ISSUE THREAD

**Issue by jmi5** [djmango/obsidian-transcription#6]
Hello - thank you for this plugin, really helpful. 

I'm noticing something strange - I have a file called "2022-12-05 Transcriptions.md", from which I have linked a Recording called `Recording 20221205092918.webm`. When the plugin returns the transcript, I see this error in the console: `Could not find transcription line for Recording 20221205092918.webm in 2022-12-05_Monday Transcriptions.md` 

Because I have the console open, I can copy out the transcript but do you have a perspective on what might be going on?

**Comment by djmango** [comment]
What's your folder structure? Could you provide a `tree` output?

**Comment by djmango** [comment]
I believe this should be fixed in the latest commit. Can you confirm?

**Comment by jmi5** [comment]
Awesome thank you, just confirmed that this fixed it - sorry I missed the email notification for your request for a `tree` output.

**Comment by djmango** [comment]
No worries! Glad to hear that it works now.
